### ISSUE TITLE
Can't Update My novels

### ISSUE THREAD

**Issue by VeneToho** [IReaderorg/IReader#102]
### Steps to reproduce

nothing much just go to the update and press the button and then the app just keeps skipping the books

### Expected behavior

it should've update my newest chapters

### Actual behavior

when press update the app tell no updates and say he skipped the books

### Crash logs

none

### IReader version

0.1.37

### Android version

Android 8

### Device

hawaii y6 2018

### Other details

none

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/IReaderorg/IReader-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.1.31](https://github.com/IReaderorg/IReader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by kazemcodes** [comment]
this is a feature of app, books would only be globally updated when you checked all chapters ad read
