### ISSUE TITLE
Errors in the bebug build for commit 1072df44bf98bc7949ab20ac29f65cca164be47e

### ISSUE THREAD

**Issue by patel-malav** [IReaderorg/IReader#104]
### Steps to reproduce

1. Checkout to the commit #1072df44bf98bc7949ab20ac29f65cca164be47e 
2. Run debug build
3. install the app

No bottom navigation bar

app crashed when swiping right probably issues in navigation for categories, 
(this could also be related to issue current app, where more then 3 categories fails)

### Expected behavior

Should be able to see the bottom navigation bar.

Swiping right should not crash the app, if there are no more categories

### Actual behavior

Cannot see bottom navigation,

App crashed on swiping

### IReader version

"0.1.38"

### Android version

Android 14

### Device

One plus 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/IReaderorg/IReader-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.1.31](https://github.com/IReaderorg/IReader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by malvpatel** [comment]
This is the commit after which it breaks

b04fd2fbe209b61c5edc6f3fb81c650e95e6b17d

**Comment by kazemcodes** [comment]
Why don't you use latest version?

**Comment by kazemcodes** [comment]
I think I fix this issue in latest commit 271b8b995e897b8d3cae3c602188be596d4ca473

**Comment by kazemcodes** [comment]
it seems there is still issue in big screens when swipe categories

**Comment by kazemcodes** [comment]
fix limited category to 3 aea3b263eee888e0acd467251066e8e7abf4a3f5
