### ISSUE TITLE
Change ui to a tachiyomi like one in the novel page

### ISSUE THREAD

**Issue by Destro9000** [IReaderorg/IReader#23]
Change novel page ui to a more Tachiyomi-like one, with the list of the chapters ecc.

**Comment by kazemcodes** [comment]
I don't like this idea, because unlike tachiyomi, in the Ireader ,the users can access the chapters while using the reading the chapters, so the chapter list in detail screen , is unnecessary, I tried to redesign the detail screen, it feels more consistent.

**Comment by Destro9000** [comment]
@kazemcodes I asked for that because it happened to me multiple times to click onto the download button near the reading one and it annoys me so much.
Besides this , I think it much more efficient to have the ui look like tachiyomi without having to click two more times just to start reading

**Comment by kazemcodes** [comment]
I feel more comfortable with the current ui
if there are more request, I will try to migrate to tachiyomi style
