### ISSUE TITLE
Add translation option

### ISSUE THREAD

**Issue by Nabeelshar** [IReaderorg/IReader#31]
I know it's far in the future (difficult) but it's going to be a killer feature.

**Comment by kazemcodes** [comment]
> I know it's far in the future (difficult) but it's going to be a killer feature.

this feature is available indirectly in the app, devs can ask users about the language they want in commands part and then save user response in preferences that is passed to source class

**Comment by kazemcodes** [comment]
> I know it's far in the future (difficult) but it's going to be a killer feature.

Do you have any idea how to add this feature to the app?🤔

**Comment by kazemcodes** [comment]
I finally found a website that has free api that has a limit of 15000 word a day.
I can use This for one word translation
https://www.translate.com/

**Comment by Snowad14** [comment]
I did not find any library made for java but you can use the Google Translate Ajax API for free ( look at googletrans on python/javascript for example)

**Comment by kazemcodes** [comment]
> I did not find any library made for java but you can use the Google Translate Ajax API for free ( look at googletrans on python/javascript for example)

can you send me it links?

**Comment by Snowad14** [comment]
js https://www.npmjs.com/package/googletrans
python https://pypi.org/project/googletrans/

**Comment by Snowad14** [comment]
I just found one for java https://github.com/jackychu0830/simple.google.translate.api (tested and work)

**Comment by kazemcodes** [comment]
in the end I decided to go with offline translation using [google MlKit translation](https://developers.google.com/android/reference/com/google/mlkit/nl/translate/package-summary) and online translation using [TranslateDict](https://t2.translatedict.com/)
