### ISSUE TITLE
Badges on novel covers vanishes

### ISSUE THREAD

**Issue by Destro9000** [IReaderorg/IReader#34]
After updating the library , the badges on the novel cover for counting the chapters read and total , vanish and cant be restored by restarting the app.

Edit: after gointo into the novel and updating from there the badge reappears but every chapter you have read will be vanished as well.

**Comment by kazemcodes** [comment]
is this problem fixed in the latest version?

**Comment by Destro9000** [comment]
Yes sorry , i forgot to close it
