### ISSUE TITLE
[Feature Request] Option to filter Bookmarked, Downloaded and Unread Chapter 

### ISSUE THREAD

**Issue by seizue** [IReaderorg/IReader#35]
Hi. Can you add an option to Filter Bookmarks, Downloaded and Unread Chapter. 

![IMG_20220603_214641](https://user-images.githubusercontent.com/25120376/171867617-3df22cda-3218-4935-9e0a-37a2fef478c0.jpg)

Similar here like in tachi. 
also thank you for the update. I like the release from preview so far ^^

![Screenshot_2022-06-03-21-51-19-81](https://user-images.githubusercontent.com/25120376/171867702-38d26094-9bc0-4c40-acc3-5edbe8ac1de9.jpg)

**Comment by kazemcodes** [comment]
what does source title and chapter number do in the display tab?

**Comment by seizue** [comment]
tbh I'm not sure, they look similar to me 😅 but looking at the SS. It's probably shows the source title (just like from WebView then chapter title??)

Source Title 
![IMG_20220608_185223](https://user-images.githubusercontent.com/25120376/172608582-a14acd52-2edd-453a-b0c2-1cd8676cc24c.jpg)

![IMG_20220608_195248](https://user-images.githubusercontent.com/25120376/172610429-c6a246c0-9279-4641-8524-9c98fb06832f.jpg)
***

Chapter Number

![IMG_20220608_185212](https://user-images.githubusercontent.com/25120376/172608682-d5afe415-d7ee-41d6-ac9a-29cac593974d.jpg)
