### ISSUE TITLE
Change splash screen based on themes (light / dark theme), instead of system (day/night)

### ISSUE THREAD

**Issue by seizue** [IReaderorg/IReader#37]
I'm using dark theme, and the "white" splash screen greets me first when I open the app (in the morning), it look a bit out of place?  specially when the theme I'm using is dark theme so it would be nice if the splash screen is based on themes (light/dark) instead of system (day/night) ..

**Comment by kazemcodes** [comment]
Actually, this splash screen is just a simple image before app loads, which means we access nothing during this time, as the the app is not even started to have theme data
If I want to add this feature that you mentioned to the app, it makes splash screen longer and probably in first 2 to 3 second it will display a blank screen which is not a good for user experience.
