### ISSUE TITLE
There still small bug in Immerse mode

### ISSUE THREAD

**Issue by seizue** [IReaderorg/IReader#38]
https://user-images.githubusercontent.com/25120376/172993724-84cfc94c-aecc-487d-9c71-43a8edddbd06.mp4

**Describe the bug**
In immerse mode, the navigation bar doesn't disappear along with reader sheet when it was tap, this occur when I swipe up to 
to view my navigation buttons. 

**To Reproduce**
1. Enable Immerse mode
2. Swipe up the navigation bar in order for the navigation button show up
3. See the Video

**Expected behavior**
The phone navigation should disappear along with the reader sheet when it was tap or should automatically disappear after 5  sec (just like in Tachiyomi)

**Smartphone (please complete the following information):**
 - OS: [Android 9]
 - Version [Stable 0.1.24]

**Comment by kazemcodes** [comment]
already fixed this problem.
