### ISSUE TITLE
Add an option to adjust the Top Margin in the Reader

### ISSUE THREAD

**Issue by rein8** [IReaderorg/IReader#39]
Add an option to adjust the Top Margin (just like in Moon+Reader) 

![IMG_20220610_183123](https://user-images.githubusercontent.com/107252378/173049186-16d65e07-1208-4ff3-8af6-d736b18c2121.jpg)

**Comment by kazemcodes** [comment]
added that in ad4d5f27caec2b1338ecb2ec3bb9b2e3b1c6b4af
