### ISSUE TITLE
[Feature Request] Ability to save custom background color and text color in Reader Screen

### ISSUE THREAD

**Issue by seizue** [IReaderorg/IReader#40]
Currently, we can modify the themes but the changes are lost as soon as we switch to another theme. I use a custom day theme and a custom night theme, so I need to manually set the colors twice a day. The ability to save custom themes can be very helpful.

**Comment by semiya5** [comment]
Theme-related and would be nice as well is font preview. Idk how hard that'd be to implement.

**Comment by kazemcodes** [comment]
both feature has been added.

**Comment by seizue** [comment]
@kazemcodes in the new preview release? 

I did check it out. I think I did confuse you. I'm talking about custom theme for the "Reader" and not the app theme 😅

I'm talking about this feature (it's from LNReader) 
![Screenshot_2022-07-11-10-30-11-58](https://user-images.githubusercontent.com/25120376/178208805-de97bd3f-594a-4a1b-ada9-fd54da0b21c3.jpg)

**Comment by kazemcodes** [comment]
It's already available in the app

**Comment by kazemcodes** [comment]
You should have mentioned it correctly ,I thought you mean the app theme

**Comment by seizue** [comment]
> 

Yea, sorry my bad xd
