### ISSUE TITLE
He does not keep the novels in the library

### ISSUE THREAD

**Issue by yemenihandsome** [IReaderorg/IReader#46]
![Screenshots_2022-07-22-07-12-54](https://user-images.githubusercontent.com/87826849/180361108-cb39fc82-86db-49fa-851e-a09a9bd24c8f.png)
**Describe the bug**
He does not update the library and repeats the narrations that have been preserved because it does not save a witness at the top of the problem that he repeats the narrations without updating Yes, the narration is repeated when saving again from the source

**To Reproduce**
1. Go to '.Keeping the novel in the library..'
2. Click on '..Make an update for the library that doesn't show the new chapters of the novels..'
3. Scroll down to '..Enter the source again, it appears that the novel is not saved in the library and is repeated again and the same problem as before..'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kazemcodes** [comment]
sorry, I can not understand what you mean exactly.
