### ISSUE TITLE
Novel cover not loading

### ISSUE THREAD

**Issue by H7XXY** [IReaderorg/IReader#49]
The covers of the novel of 1kissnovel isn't loading even after updating

1. Go to 'Explore'
2. Click on 'Sources'
3. Scroll down to 'KissNovel'
4. Open any one of them

**Expected behavior**
The novel cover's should load

**Screenshots**
![image](https://user-images.githubusercontent.com/96281738/183876533-4de3aceb-ef4d-4895-93d2-e54bfdbe59a0.png)

**Smartphone (please complete the following information):**
 - Device: [Realme Gt Neo 2 5g]
 - OS: [Android 12]

**Comment by kazemcodes** [comment]
fixed
