### ISSUE TITLE
[BUG] Chapter Not Marking Read

### ISSUE THREAD

**Issue by mystic-man-rhino** [IReaderorg/IReader#50]
**Describe the bug**
After completely reading chapter it should be marked read but this not working as expected.

**To Reproduce**

1. Go to Any Series Chapter list
2. Open Chapter and scroll till end
3. Either move to next chapter exit chapter reading page
4. Already read Chapter is still not marked read

**Expected behavior**
After reading Chapter should be marked as read

**Smartphone (please complete the following information):**
 - Device: Redmi Note 5 Pro
 - OS: Android 9.0
 - Version 0.1.27

**Comment by kazemcodes** [comment]
I don't have this problem, does this problem happen all times?

**Comment by mystic-man-rhino** [comment]
I just checked in Android 9 device it's working but my reading device is running on Android 11 in that device problem occurs. 

Might be OS issue as well.

**Comment by kazemcodes** [comment]
try cleaning app cache, I wasn't able to reproduce this bug my self.
