### ISSUE TITLE
updater not working 

### ISSUE THREAD

**Issue by pavirupa** [IReaderorg/IReader#52]
while trying to update novels in library,it is showing error books are skipped.
![IMG_20220819_091140](https://user-images.githubusercontent.com/111552496/185538274-430cfe0f-218d-490d-a628-3f0e38485c0d.jpg)

**Comment by kazemcodes** [comment]
You need to read all chapters or mark chapter as read in order to make global updater works

**Comment by Destro9000** [comment]
@kazemcodes why? Shouldn't the updater work regardless if i have or haven't read a particular novel?

**Comment by kazemcodes** [comment]
I follow the same logic as tachiyomi, because unnecessary update request for many person who have more than 100 books in library can cause the site to trigger aggressive cloudflare protection as the site thinks it's under attack

**Comment by Destro9000** [comment]
Ah ok , so it works only if you actually have read at least one chapter of the novel or all of them?

**Comment by kazemcodes** [comment]
The key point is marking all chapter as read

**Comment by sshJovian** [comment]
> The key point is marking all chapter as read

we can do it manually nah?

**Comment by kazemcodes** [comment]
Yeah, all this restrictions is only applied to global update ، single book update can be done without any restrictions

**Comment by Destro9000** [comment]
That makes the global updates useless tho. If you need to put all the chapters read for all the novels you have in the library , what's the points in having a global update?

**Comment by pavirupa** [comment]
thank you

**Comment by sshJovian** [comment]
> 

I also have the same problem but I can also understand but if you want to do that talk to the developers of [tachiyomi.org](https://tachiyomi.org/) cuz it uses Tachiyomi as the core.
