### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by rektpartyaftermath** [IReaderorg/IReader#57]
## How to use translation feature?
I tried to use it, IReader first download a zip file, after download is done, IReader just throw an error "1 of 1 task is failed" or something, then nothing happen, i try again, still the same error.
My device is oppo a37 with Android 5.1.

**Comment by kazemcodes** [comment]
There is a huge chance the problem is in your android version, I will take a look at translation feature later

**Comment by rektpartyaftermath** [comment]
I try it again, and now somehow it worked.

**Comment by rektpartyaftermath** [comment]
I remember watching the download progress last time and got that error, maybe because of that?
