### ISSUE TITLE
virustotal showing virus 

### ISSUE THREAD

**Issue by killerlearner** [IReaderorg/IReader#68]
### Steps to reproduce

Just do a quick virus check in virus total and you will find it showing virus.

### Expected behavior

Shouldn't show it

### Actual behavior

Showing virus 

### IReader version

latest 

### Android version

a12

### Device

google

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/IReaderorg/IReader-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.1.31](https://github.com/IReaderorg/IReader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by kazemcodes** [comment]
It didn't find anything for me
https://www.virustotal.com/gui/url/40087a1e8c14ab70cbe211c500fe8621adaf12865ff9c84c6ef91061330005cc/detection

**Comment by kazemcodes** [comment]
https://www.virustotal.com/gui/file/0e84c8aa7a7f0a23857b4a6a40e34d2dc56287f09cab1b0aa4606574ef3b0821?nocache=1
no virus so far

**Comment by kazemcodes** [comment]
IReader-Preview repo has a workflow that check apks for virus
https://github.com/IReaderorg/IReader-Preview/blob/master/.github/workflows/scan_release.yml
