### ISSUE TITLE
Delete downloaded chapters

### ISSUE THREAD

**Issue by Lustsifer** [IReaderorg/IReader#70]
### Describe your suggested feature

Can you add the possibility to delete downloaded chapters? It make the backup file bigger and bigger because the downloaded chapters also got backed up too.

### Other details

![Screenshot_2023-01-25-15-21-13-654_pl solidexplorer2](https://user-images.githubusercontent.com/84452966/214513516-0cbc2a28-b52f-4a36-94d5-061c16d27fbf.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/IReaderorg/IReader-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.1.28](https://github.com/IReaderorg/IReader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Lustsifer** [comment]
Wait, I actually can delete downloaded chapters but it also reset the reading state of those deleted chapters

**Comment by kazemcodes** [comment]
if chapters were deleted then because it has releation with history table in database then both of them would be deleted,
what do you think of just deleting the content of selected chapter instead of deleting whole chapter?
