### ISSUE TITLE
Support new text style

### ISSUE THREAD

**Issue by kazemcodes** [IReaderorg/IReader#77]
### Describe your suggested feature

Support new text style type
![1681884116784](https://user-images.githubusercontent.com/76521159/232992886-ec620151-531a-48ef-9d13-be7f83e4a710.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/IReaderorg/IReader-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.1.28](https://github.com/IReaderorg/IReader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by kazemcodes** [comment]
Does anyone know how to implement this?🤔

**Comment by malvpatel** [comment]
The simple possible thing i can Imagine is parse the sentences to have half of the word length made bold and rest normal

**Comment by malvpatel** [comment]
However the actual method is to, bold the first half of the word so for example, In word "Patriarch" the following part would be bolder **Pat**riarch" would be normal as we split into "Pat - ri - arch" where if there was a similar word in the paragraph such as "Patriarch Patrik" then it should be **Patri**arch **Pat**rik.


This is really similar to what we get to hear when we listen at 2x speed in tts, where first part of the word would be more clear then the end part, therefore very helpful in reading the CN webnovels

**Comment by kazemcodes** [comment]
![image](https://github.com/IReaderorg/IReader/assets/76521159/949cfd9b-5776-4617-90ab-1558b1e83534)
