### ISSUE TITLE
book cover doesn't appear on the home page

### ISSUE THREAD

**Issue by fallsdevil** [IReaderorg/IReader#98]
### Steps to reproduce

I imported some books from my storage, and the covers are not showing on the home page, but they normally appear in the "history" tab.

### Expected behavior

There is some problem, in which the book covers should appear, but they don't appear like in this image
![Screenshot_20231012_104355](https://github.com/IReaderorg/IReader/assets/142761950/ad314e31-1230-4c89-b009-1f3086b2bbce)

### Actual behavior

unfortunately, the book covers are only visible in the "history" tab.

### IReader version

0.1.37

### Android version

Android 12

### Device

Moto E22

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/IReaderorg/IReader-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.1.31](https://github.com/IReaderorg/IReader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by kazemcodes** [comment]
fixed
