### ISSUE TITLE
Regarding reading settings 

### ISSUE THREAD

**Issue by ShadowMonarch100** [IReaderorg/IReader#99]
### Describe your suggested feature

Upon opening the chapter if we click anywhere on the screen it should show reading settings like tachiyomi. Where we can change font size, color of background and other settings. So we don't have to go to settings to change it. It's a hassle and we can't see preview if we change something from settings for example if I increase font size i can't see it instantly how much i should increase or decrease the font size.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/IReaderorg/IReader-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.1.28](https://github.com/IReaderorg/IReader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by kazemcodes** [comment]
this feature is available in app, can you tell me what is version of your android?
